### ISSUE TITLE
After changing window 10 username my linux distribution setup is lost

### ISSUE THREAD

**Issue by hanzlahabib** [microsoft/WSL2-Linux-Kernel#191]
I have installed Wsl2 and Linux distribution successfully
I was having issue with window username, I just changed my window username, after doing so when I started window terminal, my Linux distribution was not shown there
[![enter image description here][1]][1]

when I separately run ubuntu from start menu, instead of loading old setup it initialized new setup and asked for username and password to get ready

I lost my previous setup of all installed distributions (ubuntu, kali)

is there any configuration where I can tell wsl2 my updated user 'name' so that instead of initializing setup from start it load stuff from there

tried google and official documentation for wsl2 and Linux distributors, nothing helped. 
 
Thanks in Advance 

  [1]: https://i.stack.imgur.com/YUGzf.png

**Comment by WSLUser** [comment]
Short answer: No.
 Slightly longer answer: distributions are installed on a per-user basis. Because you changed your username, the Microsoft Store thinks you have a new account. I suggest filing this at https://github.com/microsoft/WSL and also Feedback Hub for MS Store that MS Store should detect username changes.

**Comment by hanzlahabib** [comment]
@WSLUser  Thank you for responding, I will file this convern on WSL repo and MS store
