### ISSUE TITLE
Error on install Linux Kernel on WSL 2

### ISSUE THREAD

**Issue by hakiri** [microsoft/WSL2-Linux-Kernel#56]
folks,
How can I build a Linux Kernel and openvswitch on WSL2 Ubuntu 18.04. 

Currently, I have the following error 

$ cp -v /boot/config-$(uname -r) .config
cp: cannot stat '/boot/config-4.19.84-microsoft-standard': No such file or directory

**Comment by hakiri** [comment]
How to install generic Linux Kernel on WSL 2 (ubuntu 18.04) without having the same error :
Following this link : https://www.cyberciti.biz/tips/compiling-linux-kernel-26.html 
The error is 👍 
:~/linux-5.2.19$  cp -v /boot/config-$(uname -r) .config
cp: cannot stat '/boot/config-4.19.84-microsoft-standard': No such file or directory

**Comment by Biswa96** [comment]
There is no `/boot` in WSL. Read the [readme file](https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/README-Microsoft.WSL2).

**Comment by hakiri** [comment]
So, how to build a new kernel in such a situation  !!

**Comment by Biswa96** [comment]
READ THE README FILE.

**Comment by hakiri** [comment]
Readme file describes how to build WSL2-Linux-Kernel. The question is how to build Linux Kernel from http://cdn.kernel.org not WSL2-Linux-Kernel. If you have idea to share OK , otherwise don't replay to the comment !!

**Comment by rssfed23** [comment]
@hakiri you cannot do this from within WSL itself. WSL is effectively a docker style container and has no access to the thin VM that's running the MS Linux Kernel. 
To replace the kernel, you'd have to build your own new vm, with all the MS bits that allow the kernel to work as WSL and then create a new distro using that kernel.

So in short; you can't do what you're trying to do easily. You can compile a kernel in WSL easily but you cannot then go and use that kernel as the WSL2 kernel is what people are saying.

@Biswa96's answer is correct. You asked how to build a new kernel and the readme describes how to build a new kernel. What the readme does not describe is how to take that kernel you built and use it as the host kernel for your WSL container, because this can not be done easily (I can't find any instructions online how to and the inner-workings of WSL on the windows side are closed source and not documented).

**Comment by mwsealey** [comment]
The %userprofile%\.wslconfig configuration file will do it. I assume you could symlink /boot to somewhere in a Windows drive and then the kernel would be outside the VHD and accessible to the VM for boot.

https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18945
