### ISSUE TITLE
how to make 'initrd.img'

### ISSUE THREAD

**Issue by taxueliuyun** [microsoft/WSL2-Linux-Kernel#7]
cmd: sudo mkinitramfs 4.19.52-microsoft-standard+ -o initrd.img (Ubuntu18.04)
my initrd.img size is 10,037,317, lxss/tools/initrd.img size is 38,400, they are unmatched.
how to build it, thanks?

**Comment by kdrag0n** [comment]
WSL 2 doesn't boot like a conventional Linux system. Its ramdisk only contains a single file: init. This init is not systemd or any other standard init system; it's Microsoft's custom minimal VM init which is responsible for mounting amd spawning the container init (located in `C:\Windows\System32\lxss\tools`) when it detects a new disk and handling some basic tasks upon request (such as terminating all the containers). The container init communicates with Windows and proceeds to set up DrvFS over 9P, namespaces, cgroups, and then finally chroots into the new distro to create a container.

A conventional distro's init with systemd and all won't work on WSL because it doesn't know how to communicate with Windows over a vsock or handle WSL distro containers. That means you won't be able to install or convert distros, spawn a shell, or perform any of the tasks you'd normally expect WSL to do — it'd just be a VM with systemd running, stuck waiting for a valid rootfs and eventually timing out.

Unfortunately, both of Microsoft's init implementations (ramdisk/utility VM and container) are closed-source. Perhaps they could make the source code for these available in the future, although I think that's somewhat unlikely given their track record with WSL 1.

**Comment by taxueliuyun** [comment]
thanks kdrag0n, I added andriod binder driver config to config-wsl, and "make KCONFIG_CONFIG=Microsoft/config-wsl". replace vmlinux to lxss/tools/kernel, it works, but 'dev/binder' can't load.

**Comment by Biswa96** [comment]
I don't know what the relation between `initrd.img` file and Android binder driver. But I do know that the `init` in `initrd.img` file is different from the actual `System32/lxss/tools/init` file. This command may help `cpio -i -F initrd.img`.

The `init` in `initrd.img` file only configures mount points, talks to AF_VSOCK, adds network interfaces IP address, routing table etc. It just prepares/initializes the ext4.vhdx file and mounts the actual `init` file, devtmpfs, proc, sys etc.

**Comment by taxueliuyun** [comment]
thanks Biswa96, now I know initrd.img's role.Maybe I am looking for the wrong direction. My purpose is to load android binder driver and ashmem driver. I have confirmed the vmlinux I made contains binder driver code by hopper, replace vmlinux to System32/lxss/tools/kernel, when I run Ubuntu in WSL2, dev/binder did not appear.

**Comment by benhillis** [comment]
The initrd.img that WSL2 uses is not produced from this repo.

@taxueliuyun - I am not sure if devtmpfs will surface binder or ashmem.  You will likely need to call mknod with the major / minor version on them to create them.

**Comment by taxueliuyun** [comment]
thanks @benhillis.
